### PR TITLE
Make Locked Displays and Stands Unbreakable

### PR DESCRIPTION
**Pull request by AllenSeitz**

### CODE REVIEW

**Comment by wildcardgamez** [comment]
It looks great! There are a few changes I'd like to recommend though:
1. Can you make it so when checking if it's locked, it will also check that the player is not in creative mode? If somebody griefs by leaving locked card stands and displays everywhere, I'd like to leave a way for admins to destroy them as if they were not locked.
2.  Can you add in the message translation text "block.buddycards.card_display.lock" when somebody tries to break a locked display, that way they know that it is locked? As well as for the card stand.

I also hope you understand that I was extremely hesitant about allowing the contribution, as it would mean this is no longer solely my mod, which worries me a little bit. Do understand when it comes to contributions, I will only allow changes that fix bugs or issues, and that I do not want new content that I do not personally plan. Thanks for deciding to contribute to the project!

**Review by wildcardgamez — APPROVED** [review]
Looks great! I'll merge and add it in the next update, I'm waiting until I can fix the patchouli book until I do another update.

**Comment by AllenSeitz** [comment]
It's fine. It's still 100% your mod. I'm giving you this freely and I don't expect anything for it. (And if this project is (c) you, all rights reserved, then you own it now.) People have surprised me with pull requests to my projects before and it's a joy.

Those two tweaks were approximately one line each. 👍

**Comment by wildcardgamez** [comment]
Thanks for contributing!

**Comment by AllenSeitz** [comment]
You're welcome!

**Pull request merged**
